### ISSUE TITLE
Latest release (1.4.1) crashes on launch

### ISSUE THREAD

**Issue by cravl-dev** [BoogieMonster1O1/useful-utilities#3]
Versions:
---------------
Minecraft: 1.16.4
Fabric Loader: 0.10.8
Fabric API: 0.27.1+1.16
Fabric Language Scala: 0.3.2.12

Useful Utilities: 1.4.1

Description of issue:
---------------
Latest release of everything crashes on startup even with no other mods; rolling back to Useful Utilities 1.4.0 launches with no problems.

---------------
<details>
<summary><b>Minecraft Log</b></summary>

Mods:
  [✔️] fabric-api-0.27.1+1.16
  [✔️] fabric-language-scala-0.3.2.12-fat
  [❌] useful-utilities-1.4.0.jar (disabled)
  [✔️] useful-utilities-1.4.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/[username]/Documents/programs/Minecraft/MultiMC/instances/Mod Isolation - Fabric 1.16/.minecraft --assetsDir C:/Users/[username]/Documents/programs/Minecraft/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms6144m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 23000

Using onesix launcher.

[17:20:49] [main/INFO]: Loading for game Minecraft 1.16.4
[17:20:49] [main/INFO]: [FabricLoader] Loading 46 mods: minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, fabric-networking-blockentity-v0@0.2.5+6a2618f53a, fabric-renderer-api-v1@0.3.3+6a2618f53a, fabric-keybindings-v0@0.2.0+6a2618f53a, jankson@3.0.1+j1.2.0, fabric-command-api-v1@1.0.9+6a2618f53a, fabricloader@0.10.8, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-structure-api-v1@1.1.1+f1d8af063a, fabric-renderer-indigo@0.4.3+6a2618f53a, fabric-containers-v0@0.1.8+6a2618f53a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-item-api-v1@1.2.0+6a2618f53a, libgui@3.0.0-beta.1+1.16.2-rc2, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.4.0+6a2618f53a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-language-scala@0.3.2.12, usefulutilities@1.4.1, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, fabric-resource-loader-v0@0.3.2+1944f3e03a, fabric-textures-v0@1.0.5+6a2618f53a, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-biome-api-v1@3.1.0+2e23b97c3a, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-registry-sync-v0@0.7.1+285766753a, fabric-commands-v0@0.2.0+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+6a2618f53a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric@0.27.1+1.16, fabric-particles-v1@0.2.2+6a2618f53a, fabric-item-groups-v0@0.2.1+6a2618f53a, fabric-models-v0@0.1.1+6a2618f53a, fabric-networking-v0@0.1.10+6a2618f53a, fabric-object-builders-v0@0.7.1+6a2618f53a
[17:20:49] [main/WARN]: Mod `fabric-language-scala` (0.3.2.12) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[17:20:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/camer/Documents/programs/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[17:20:51] [main/WARN]: Reference map 'useful-utilities-refmap.json' for usefulutilities.mixins.json could not be read. If this is a development environment you can ignore this message
[17:20:51] [main/FATAL]: Mixin prepare failed preparing MixinGameMenuScreen in usefulutilities.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'io.github.boogiemonster1o1.usefulutilities.mixin.MixinGameMenuScreen' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'io.github.boogiemonster1o1.usefulutilities.mixin.MixinGameMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.8.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.8.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_251]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:222) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'io.github.boogiemonster1o1.usefulutilities.mixin.MixinGameMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	... 23 more
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [usefulutilities.mixins.json:MixinGameMenuScreen] from phase [DEFAULT] in config [usefulutilities.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:590)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:517)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:222)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'io.github.boogiemonster1o1.usefulutilities.mixin.MixinGameMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514)
	... 20 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'io.github.boogiemonster1o1.usefulutilities.mixin.MixinGameMenuScreen' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848)
	... 23 more
Exiting with -1
Process exited with code -1.

</details>

**Comment by BoogieMonster1O1** [comment]
Fixed in 1.4.2
https://www.curseforge.com/minecraft/mc-mods/useful-utilities/files/3130557
