### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Nayrin** [BoogieMonster1O1/useful-utilities#5]
java.lang.RuntimeException: Failed to setup mod Useful Utilities (C:\Users\sex\AppData\Roaming\.minecraft\mods\useful-utilities-1.5.0.jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupMods(FabricLoaderImpl.java:460)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:335)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:111)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.Exception: Could not find adapter 'scala' (mod usefulutilities!)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage.add(EntrypointStorage.java:153)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupMods(FabricLoaderImpl.java:456)
	... 5 more

**Comment by BoogieMonster1O1** [comment]
Install fabric language scala
